### PR TITLE
No-Area Subscriptions

### PR DESCRIPTION
**Pull request by versx**
Allows users to subscribe to Pokemon, PvP, Raids, Quests, or Invasions with no city/area selected in order to use only distance for subscriptions.

If the user does not have a distance set upon creating the subscription, they will be informed to set one and the request cancelled until they do.

Omitting the city parameter will not assume `All` areas anymore when subscribing.

### CODE REVIEW

**Comment by versx** [comment]
Anyone test?

**Comment by versx** [comment]
Anyone test?

**Comment by versx** [comment]
Anyone test?

**Comment by bradders2000** [comment]
I'm really glad to see this PR exists. Thank you!
It's the thing I instantly noticed was missing after trying WhMgr out for the first time a couple of days ago in what is basically a setup where it would only be used for individual user subscriptions. Using 'master', I thought it was a bug that I'd set my distance and location and was still getting notification for my entire area (using .pokeme all 100).
I manually merged (not using git) into your current 'master' and it appears to be working. I've seen a few places where the lack of an area makes for weird error/feedback messages, but they're easily fixed.
I wasn't keen on the set-distance command needing both distance and location, so opted to split location into another command (set-location). You don't want to have to remember your location in order to change the distance.
It's also nicer if location is included in the .info print out, so I added that.

**Comment by Dewpg** [comment]
I had issues as Master was on migration 4 and built to a different folder, so I gave up on testing it.  My bad.  I think this was created at my request in the first place, I should have tested it sooner.

**Comment by versx** [comment]
> I'm really glad to see this PR exists. Thank you!
> It's the thing I instantly noticed was missing after trying WhMgr out for the first time a couple of days ago in what is basically a setup where it would only be used for individual user subscriptions. Using 'master', I thought it was a bug that I'd set my distance and location and was still getting notification for my entire area (using .pokeme all 100).
> I manually merged (not using git) into your current 'master' and it appears to be working. I've seen a few places where the lack of an area makes for weird error/feedback messages, but they're easily fixed.
> I wasn't keen on the set-distance command needing both distance and location, so opted to split location into another command (set-location). You don't want to have to remember your location in order to change the distance.
> It's also nicer if location is included in the .info print out, so I added that.

Thank you, I don't know how I missed your comment but I appreciate you testing. I'd like to eventually rework the set distance/location parts so you can select between multiple pre-set locations tbh.

**Pull request merged**
