### PR TITLE
Fix Duplicate Pokemon

### PR DESCRIPTION
**Pull request by versx**
…on-IV and one with IV)

### CODE REVIEW

**Comment by versx** [comment]
Anyone test?

**Comment by cks85** [comment]
If for whatever reason the scanner sends twice the pokemon with iv, I understand both will be alerted?
Same if twice without IV (both pass) then a potential third with IV will never be alerted?

Maybe the check should be made on a key with EncounterId and something like Weight (any encounter-scanned data), and a be something like (totally untested..) :
```
if (!pokemon.Weight && _processedPokemon.ContainsKey(pokemon.EncounterId) || pokemon.Weight && _processedPokemon[pokemon.EncounterId].Weight)
                {
                    return;
                }
if (!_processedPokemon.ContainsKey(pokemon.EncounterId))
                {
                    _processedPokemon.Add(pokemon.EncounterId, pokemon);
                }
if (pokemon.Weight && !_processedPokemon[pokemon.EncounterId].Weight)
                {
                    _processedPokemon.Remove(pokemon.EncounterId, pokemon);
                    _processedPokemon.Add(pokemon.EncounterId, pokemon);
                }
```

**Comment by versx** [comment]
> If for whatever reason the scanner sends twice the pokemon with iv, I understand both will be alerted?
> Same if twice without IV (both pass) then a potential third with IV will never be alerted?
> 
> Maybe the check should be made on a key with EncounterId and IsMissingStats, and a be something like (currently testing, so not 100% sure..) :
> 
> ```
>                 if (_processedPokemon.ContainsKey(pokemon.EncounterId) && (pokemon.IsMissingStats || !pokemon.IsMissingStats && !_processedPokemon[pokemon.EncounterId].IsMissingStats))
>                     return;
>                 if (!_processedPokemon.ContainsKey(pokemon.EncounterId))
>                     _processedPokemon.Add(pokemon.EncounterId, pokemon);
>                 if (!pokemon.IsMissingStats && _processedPokemon[pokemon.EncounterId].IsMissingStats)
>                 {
>                     _processedPokemon.Remove(pokemon.EncounterId);
>                     _processedPokemon.Add(pokemon.EncounterId, pokemon);
>                 }
> ```

Logic seems fine to me, I just have one simplification to suggest:
```
                 if (_processedPokemon.ContainsKey(pokemon.EncounterId) && (pokemon.IsMissingStats || !pokemon.IsMissingStats && !_processedPokemon[pokemon.EncounterId].IsMissingStats))
                     return;
                 if (!_processedPokemon.ContainsKey(pokemon.EncounterId))
                     _processedPokemon.Add(pokemon.EncounterId, pokemon);
                 if (!pokemon.IsMissingStats && _processedPokemon[pokemon.EncounterId].IsMissingStats)
                 {
                     _processedPokemon[pokemon.EncounterId] = pokemon;
                 }
```

**Comment by Petap0w** [comment]
seems to be working (although it's difficult to actually know if there has been duplicates - but no users have been complaining).
but there is a need of clearing the _processedPokemon old entries or it's just going to eat up memory?

**Comment by versx** [comment]
> seems to be working (although it's difficult to actually know if there has been duplicates - but no users have been complaining).
> but there is a need of clearing the _processedPokemon old entries or it's just going to eat up memory?

I'll try and test it today, I usually get a consistent duplicate every 10th 100% or so.
Maybe clearing it every 30-60 minutes would be a best? I'll run it in the debugger and see how much it increases.

**Comment by Petap0w** [comment]
> Maybe clearing it every 30-60 minutes would be a best? I'll run it in the debugger and see how much it increases.
been running 3 hours here and instance is at 2.1gb

**Comment by versx** [comment]
> > Maybe clearing it every 30-60 minutes would be a best? I'll run it in the debugger and see how much it increases.
> 
> been running 3 hours here and instance is at 2.1gb
> also what is done in Poracle is that only encounterId and any other encountered value is store instead of the full pokemon load (we don't do anything with it afterwards anyway)

Oof yeah that's a lot, we could also do similar to Poracle. Since your routine only uses the `IsMissingStats` property (boolean) we could just change the `_processedPokemon` type to `Dictionary<string, bool>` which should use a significant amount less in memory.

**Pull request merged**
